version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: newsfeed-postgres
    environment:
      POSTGRES_DB: newsfeed
      POSTGRES_USER: newsfeed
      POSTGRES_PASSWORD: newsfeed123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsfeed-network

  redis:
    image: redis:7-alpine
    container_name: newsfeed-redis
    ports:
      - "6379:6379"
    networks:
      - newsfeed-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsfeed-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/newsfeed
      SPRING_DATASOURCE_USERNAME: newsfeed
      SPRING_DATASOURCE_PASSWORD: newsfeed123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - newsfeed-network

volumes:
  postgres_data:

networks:
  newsfeed-network:
    driver: bridge