spring:
  application:
    name: newsfeed

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/newsfeed}
    username: ${SPRING_DATASOURCE_USERNAME:newsfeed}
    password: ${SPRING_DATASOURCE_PASSWORD:newsfeed123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    com.example.newsfeed: DEBUG
    org.springframework.data: DEBUG